### ISSUE TITLE
[Core Contributors] Recruit 5 new Forum Mods (CC role)

### ISSUE THREAD

**Issue by sarina** [openedx/community-wg#52]
We have specified the forum mod role as a Core Contributor role, as detailed in https://github.com/openedx/community-wg/issues/50

Forum mod responsibilities are detailed here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3278995469/Forums+Moderation+on+Discourse

We will make a forum post inviting people to volunteer for this role. We may want to wait until https://github.com/openedx/open-edx-proposals/pull/275 is reviewed and merged before adding new people to the role.

**Comment by sarina** [comment]
My preference is to hold off until OEP-54 is accepted, and another preference is to recruit some moderators who are not already in an existing CC role in order to expand the program.

**Comment by sarina** [comment]
I'm working on identifying non-Core Contributor community members who the existing moderation team is okay with joining. I have messaged the mods privately and we are looking at some candidates; when we're in agreement, I'll reach out to those people asking if they want to participate.

If we can't fill all 5 slots, we'll ask for people who are interested in the role to self-nominate.

**Comment by sarina** [comment]
I proactively contacted 4 outstanding forum members to see if they'd be interested, but only one replied (he said yes). I didn't hear back from the other 3.

I posted a general call here: https://discuss.openedx.org/t/call-for-forum-moderators/6592 - no one has replied or reached out to me. 

Does anyone have any thoughts about ways we could get more traction on this?

**Comment by sarina** [comment]
Hi @regisb @antoviaque @nizarmah - I'm tagging you as you were participants in this ticket's parent, https://github.com/openedx/community-wg/issues/50

I proactively contacted 4 outstanding forum members to see if they'd be interested, but only one replied (he said yes). I didn't hear back from the other 3.

I posted a general call here: https://discuss.openedx.org/t/call-for-forum-moderators/6592 - no one has replied or reached out to me. 

Does anyone have any thoughts about ways we could get more traction on this? We have 7 moderators, space for 15. More moderators are better - even someone spending just a bit of time every week is helpful. Our forums are also not particularly high-traffic.

**Comment by nizarmah** [comment]
@sarina @antoviaque @regisb I have some thoughts. Please note that I'm thinking out loud, so don't hold back any comments, you would be helping me refine my thoughts. 

> Does anyone have any thoughts about ways we could get more traction on this?

Can we create custom badges on Discourse for forum moderation, maybe one which gets awarded every year a member spends on forum moderation?
"Having something to show" for that forum moderation might be encouraging for some to volunteer a little bit of their time towards it.
Also, it might encourage partners and providers to ask some of their members to have such a presence (or badge) on the forums.
This is all hypothetical, though. But there's no doubt that some members participated in the "doc-athon" for these badges.

Also, in case finding moderators that are willing to volunteer their time is hard at the moment, coupling this role with another non-technical core contributor role, which members might be more interested in, might help? 
Although I do have some doubts about this suggestion because it might require additional context switching. But if there's something that requires being aware of different updates, such as a marketing related non technical core contributor role, it might be a good option.

And finally, in case we do end up with a little number of moderators, we might be able to encourage the community to interact with the forum in a moderator-like role without the responsibilities.
Members can be encouraged to contribute to the moderation of the forum by granting Discourse badges to every correctly flagged post and/or greeting a new member (after an initial post).
After certain number of "correctly-flagged" posts or "greets", each having a specific point value, those members can be rewarded by an "Open edX" shirt or a pin or some stickers? I'm not sure if these are available options, but they definitely help encourage action.

**Comment by sarina** [comment]
For now, I have found 3 new moderators who are excited, so I am pleased with that right now. We can continue to look for more but adding and supporting 3 people will be a good start.

> Can we create custom badges on Discourse for forum moderation, maybe one which gets awarded every year a member spends on forum moderation?

I'm not sure how to do the "per year" award, but I am happy to make a badge.

> Also, in case finding moderators that are willing to volunteer their time is hard at the moment, coupling this role with another non-technical core contributor role, which members might be more interested in, might help?

I don't have an idea of what this might look like.

> After certain number of "correctly-flagged" posts or "greets", each having a specific point value, those members can be rewarded by an "Open edX" shirt or a pin or some stickers? I'm not sure if these are available options, but they definitely help encourage action.

I would love to be able to award physical items, but it has been a problem in the past that many countries don't have a great customs track record. We ceased giving t-shirts for the edX bug bounty program because it felt unfair that a number of people weren't ultimately receiving their shirt.

> : how can the Open edX community publicly acknowledge the contributions of its CCs?

I would love ideas there, @regisb - or maybe @nedbat could take a moment to weigh in. I have not spent time on internet forums (I know, this is kind of weird) so I'm unfamiliar with the dynamics of forums, what "reputation" or "street cred" is within the ecosystem. 

> the job remains fun and engaging

is there a way for forum mods to help each other out with their role? I have not seen any traffic in the Staff topic or the Slack chat. Is there a way to get more people involved here (maybe tenured mods could be more diligent in responding?)

**Comment by sarina** [comment]
After I wrote this, I realized I think all moderators should weigh in here. Let's transfer this discussion to https://discuss.openedx.org/t/a-more-lively-rewarding-moderator-experience/6630 - I'm going to close this ticket so that we don't bifurcate the discussion.
